language: node_js
node_js:
- '5.0'
before_deploy: npm run build
deploy:
  provider: npm
  api_key:
    secure: KOag4ahg5GPAuq3/BI7ighqz+EyVu/XQwmhZgZB6cQMqp946IxlvEn7RYNjbIbIST7BGZHA84v8VMAK93maRMb9yvNydsQZmlLi4Wpg2VIg5Vi4e9C+gXwbLMBK/UQQYMa4eamGzwOdVByv86jBwVnwaTJ2dFY9fSGzL5ciC5q0=
  on:
    tags: true
    branch: master
