language: node_js
node_js:
- '0.12'
before_deploy: gulp build
deploy:
  provider: s3
  access_key_id: AKIAIUBRKBVSD3LAFBUQ
  secret_access_key:
    secure: V40rWpz/ruqzI+5eXYCcJSmkDcaMgkhadJ1wMS/rmlFZvEshdz9i4qDQtp347djAubWCjO8rcGJkK0AFBSxMnWu6UHYjrkZ80eAr2MFaJKjgMLIzJqZqDTHBvPlMpFuVUnVD8WWwc7vHRLa6hSkozov9KWuBVZapD58fqMcPnOk=
  bucket: cdn.biojs.net
  upload-dir: msa/latest
  acl: public-read
  detect_encoding: true
  skip_cleanup: true
  local-dir: build
  region: eu-west-1
  on:
    repo: greenify/msa
